name: Update GitHub Profile Metrics

on:
  schedule:
    - cron: "0 6 * * *"

  workflow_dispatch:

  push:
 *  branches:
      - main
    paths*
      - ".github/workflows/metric*.yml"

permissions:
  contents: wr*te

concurrency:
  group: github-p*ofile-metrics
  cancel-in-progress* true

jobs:
  generate-metrics:
 *  name: Generate GitHub profile me*rics
    runs-on: ubuntu-latest

 *  steps:
      - name: Generate pr*file overview
        uses: lowlig*ter/metrics@latest
        with:
 *        token: ${{ secrets.METRICS*TOKEN }}
          user: FGaleti
 *        filename: metrics/profile-*verview.svg

          template: c*assic
          config_timezone: A*erica/Sao_Paulo
          config_a*imations: true
          config_pa*ding: 5%
          config_output: *vg
          config_twemoji: true
*          base: header, activity, *ommunity, repositories, metadata

*         repositories_forks: false*
      - name: Generate contributi*n calendar
        uses: lowlighte*/metrics@latest
        with:
    *     token: ${{ secrets.METRICS_TO*EN }}
          user: FGaleti
    *     filename: metrics/contributio*-calendar.svg

          template:*classic
          config_timezone:*America/Sao_Paulo
          config*animations: true
          config_*adding: 5%
          config_output* svg
          config_twemoji: tru*

          base: ""

          re*ositories_forks: false

          *lugin_isocalendar: true
          *lugin_isocalendar_duration: full-y*ar

      - name: Generate languag* metrics
        uses: lowlighter/*etrics@latest
        with:
      *   token: ${{ secrets.METRICS_TOKE* }}
          user: FGaleti
      *   filename: metrics/devops-langua*es.svg

          template: classi*
          config_timezone: Americ*/Sao_Paulo
          config_animat*ons: true
          config_padding* 5%
          config_output: svg
          config_twemoji: true

          base: ""

          repositories_forks: false

          plugin_languages: true
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_languages_details: percentage